# Generated by Django 4.1 on 2024-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF Document'), ('video', 'Video'), ('music', 'Music'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
